### ISSUE TITLE
What to use?

### ISSUE THREAD

**Issue by MaxNoe** [pep-dortmund/member-database#1]

**Comment by ccauet** [comment]
What is the scope of this application? Should it act as a backend only or provide a UI?

**Comment by bixel** [comment]
I think a minimal UI for internal use would be nice. Maybe this would also be a good point to try NoSQL, since we probably add quite a few fields in the future. We could use an app layout similar to pars.

**Comment by MaxNoe** [comment]
Both, right now this repo is meant for discussion.

We want to have an easy to use UI for us and in the long run the posibility for members to change their data over a web-ui

**Comment by ccauet** [comment]
Ok, then I would go with Flask + MongoDB as a first shot

**Comment by bixel** [comment]
Do you have any experience with MongoDB? Maybe some recommended tutorials (except for google's top hits)? I tried couchdb once and had some difficulties getting startet.

**Comment by ccauet** [comment]
Yes, I have some experience, it's insanely easy to start with. Installation as a `homebrew` service, then using `pymongo` as Python API (http://api.mongodb.org/python/current/tutorial.html).

**Comment by ccauet** [comment]
See `db.py` for a simple MongoDB API and `README.md` for installation instructions. I will add more functionality, fault tolerance, and tests in the future

**Comment by bixel** [comment]
See README.md for the ideas we tried to fix now during the last "Klausurtagung".
