### ISSUE TITLE
Add CORS for all pep-dortmund domains and very basic API for Events

### ISSUE THREAD

**Issue by The-Ludwig** [pep-dortmund/member-database#160]
I'd like to reference how many  free places there are for an event on the main pep-homepage. 
The best approach for that is to generate a basic api like:
```sh
> curl https://registration.pep-dortmund.org/events/15/info
{ 'free-places':  15, 'registration-open': true, ...}
```
And for that to work on other pep-websites, we have to add CORS:
`Access-Control-Allow-Origin: https://*.pep-dortmund.de https://*.pep-dortmund.org`

**Comment by The-Ludwig** [comment]
@maxnoe before I start to try to implement that: Any thoughts on that? For the api endpoint, I guess I have to add a path in `member_database/events/__init__.py`. I have no idea for the CORS thing, though

**Comment by maxnoe** [comment]
The API is already there. However events do currently not include a "free-places" field, but that would be easy enough to add. CORS is not a concern here, since reading event info is public and does not need authentication.

**Comment by The-Ludwig** [comment]
@maxnoe please see #162 , which adds this feature, including CORS (which is needed, as we discussed).
