### ISSUE TITLE
Enable basic auth for api endpoints

### ISSUE THREAD

**Issue by MaxNoe** [pep-dortmund/member-database#19]
Currently it's not possible to get data using commandline utilities like curl or httpie, even requests sessions do not work.

something like `curl -u <user> <url>/members`  should work and would make testing during developement much easier

**Comment by MaxNoe** [comment]
This is described here:
https://flask-login.readthedocs.io/en/latest/

**Comment by bixel** [comment]
Ok that sounds good. Actually I did this using `httpie`'s sessions which is obviously a bit annoying because you have to copy csrf tokens around...
