### ISSUE TITLE
What do we want to achieve?

### ISSUE THREAD

**Issue by maxnoe** [pep-dortmund/member-database#2]
Some Ideas of the meeting in Essen and before:
- Let members change their data (employer, email-address etc.)
- Easier access for us, add new members, edit, customized mails etc.

**Comment by ccauet** [comment]
some ideas


 - explore other members  
- membership fee information/statistics
 - interface to https://github.com/pep-dortmund/personalized-emails
   - email campaigns
   - newsletter
   - yearly reports
