### ISSUE TITLE
shorter shortlink

### ISSUE THREAD

**Issue by The-Ludwig** [pep-dortmund/member-database#202]
our shortlinks for events are already nice, but not nice enough to e.g. print them on paper for registration: 
```
registration.pep-dortmund.org/events/SHORTLINK/registration
```
is not as nice as 
```
registration.pep-dortmund.org/SHORTLINK
```

**Comment by maxnoe** [comment]
Yes, true, however that would break the separation of the different packages / blueprints

**Comment by The-Ludwig** [comment]
> Yes, true, however that would break the separation of the different packages / blueprints

Yes, I also thought of this... I am sure it is fixable somehow anyway. Or maybe something like `registration.pep-dortmund.org/e/SHORTLINK`

**Comment by maxnoe** [comment]
Solved now by installing an URL shortener on the pep server that can shorten arbitrary urls
