### ISSUE TITLE
Write unit tests

### ISSUE THREAD

**Issue by MaxNoe** [pep-dortmund/member-database#22]
- [x] Add pytest config
- [x] Write tests
  - [x] events
  - [x] auth
- [x] setup CI on travis

**Comment by MaxNoe** [comment]
Test config three simple tests were added in #30.

We need tests for the authentication system and the event system.

**Comment by bixel** [comment]
CI on travis will be added via #32

**Comment by MaxNoe** [comment]
We have a basic set of unit tests and CI in place. Closing this now.

Will open specific issues for areas where coverage is lacking.
