### ISSUE TITLE
Modularize vuejs part

### ISSUE THREAD

**Issue by bixel** [pep-dortmund/member-database#39]
So right now an individual vue-app is added for each input field: https://github.com/pep-dortmund/member-database/blob/b95adebdd08643dbf2ede03e834b1182d3495f58/database/static/js/latex_widget.js#L42-L54
This works of course, but at some point it would be nice to modularise this a little bit more.

One could think of input field connections like in the old PARS interface: You select the "Bachelor" degree and the title of the thesis field becomes "Bachelor-thesis" 😎

This is very low priority of course.

**Comment by The-Ludwig** [comment]
I don't really get why we need vuejs (<3) to render LaTeX? Seems a little bit of an overkill to render the title...

**Comment by maxnoe** [comment]
Agree, a simple on change vanille js callback on the field could do the same

**Comment by The-Ludwig** [comment]
Nice, vanilla Js installation instruction here: http://vanilla-js.com/ ;)

**Comment by maxnoe** [comment]
Addressed in #175
