### ISSUE TITLE
SQL vs. NoSQL

### ISSUE THREAD

**Issue by MaxNoe** [pep-dortmund/member-database#5]
A member database sounds quite like a classical use case for SQl.

Please discuss.

**Comment by ccauet** [comment]
I like NoSQL far more than SQL as it frees you from defining the DB structure beforehand and allows for very flexible and agile development. Nevertheless we should define the DB API in a way that makes it easy to change the underlying DB model w/o touching anything else.

So, my vote: NoSQL :+1:, SQL :-1:

**Comment by bixel** [comment]
I agree with you @ccauet. I would expect some - maybe many - changes to the DB in the future even if we define a detailed structure now. Even if there are tools for SQL DB migrations they come with some additional work, NoSQL doesn't. :arrow_right:  NoSQL :+1:, SQL :-1:
(If we have a well working NoSQL example we could also move to NoSQL for pars :-) )

**Comment by bixel** [comment]
Some time has passed since the first discussion of this. We actually decided to use SQL + proper DB migrations now as (beside other reasons) this is documented in the flaskmegatutorial.
