### ISSUE TITLE
Registrtation test

### ISSUE THREAD

**Issue by chrbeckm** [pep-dortmund/member-database#66]
- AG Schneider counts as E4b?
- email@test is possible, could it be checked for `.` in domain?
- if the external place is chosen, maybe there is a place to specify where it was written

**Comment by MaxNoe** [comment]
1. yes, see https://www.e4.physik.tu-dortmund.de/cms/de/Lehrstuhl/
2. technically, that's a valid email address (e.g. used in <user>@localhost. But we should check this. In PARS we forced `@tu-dortmund.de` email addresses
3. Having optional fields in the form would complicate the code alot, I think we'll skip this
