### ISSUE TITLE
Add "request token" button to login page

### ISSUE THREAD

**Issue by bixel** [pep-dortmund/member-database#72]
The login button is relatively dominant in the navigation bar. Registrants could expect this button to provide some login for their registrations as well. So maybe for now we could just add a email-field in the login form to request a main containing links to all active registrations for that email.

**Comment by MaxNoe** [comment]
Maybe for now just changing the label to "Administrator Login" and making it "secondary" will provide a short term improvement?

**Comment by The-Ludwig** [comment]
@maxnoe I agree, maybe let's just remove the login button completely. This is primarily a user-facing application. Administrators can remember the url.
With the DSGVO data request, we basically already have the feature for  looking at past and active registration, although in ugly form.
