### ISSUE TITLE
Editing an Event might override Registrations

### ISSUE THREAD

**Issue by bixel** [pep-dortmund/member-database#75]
If new EventRegistrations come in while an Event is edited, saving the Event will override the new Registrations.

**Comment by MaxNoe** [comment]
Could you elaborate what exactly happens here? Is the ID of an even changed when it is edited?

**Comment by MaxNoe** [comment]
What do you mean by overrides the registration?

**Comment by bixel** [comment]
The EventRegistrations as of the time you enter the Event editing form will be pre-filled into the form. If the Event editing form is saved, this pre-filled list will be updated, regardless whether a new EventRegistration for that event came in in the mean time.

**Comment by bixel** [comment]
Ok, it looks like hiding the `registrations` field in the admin form will prevent any updates of the reference table.

**Comment by MaxNoe** [comment]
Oh, now I understand. I think you can also exclude attributes from being saved
