### ISSUE TITLE
Create different User groups

### ISSUE THREAD

**Issue by karl9000** [pep-dortmund/member-database#79]
Users should have the right to see every information of the database. Grouping of users with same rights could help in that matter

**Comment by MaxNoe** [comment]
> Users should have the right to see every information of the database. 

No they shouldn't

What do you mean here exactly?

> Grouping of users with same rights could help in that matter

Roles could be interpreted as groups, e.g. all users that share a certain role.
I.e the admin group, all users with role admin.

**Comment by bixel** [comment]
> Users should have the right to see every information of the database.
I think we could come up with per-event access levels that can be assigned to users. So if you are in charge of a specific event, you should only be able to see the information concerning this event, and nothing more.
