### ISSUE TITLE
Implement data request

### ISSUE THREAD

**Issue by maxnoe** [pep-dortmund/member-database#8]
Add the possibility to send a mail or mail with pdf attachment containing all information we have about a member on request. (GDPR data request)

- [x] Add an endpoint with method post and form data email.

- [ ] Add a template for the email

- [x] Write the queries that dump all data we have for a `Person`

**Comment by bixel** [comment]
Actually, @MaxNoe already created this issue @beckstev :-)

I think you can essentially copy the endpoint `request_edit` (https://github.com/pep-dortmund/member-database/blob/master/database/__init__.py#L150-L173) and use e.g. `pprint.pformat` to write a mail with everything that is somehow connected to the person that requests the data.

**Comment by beckstev** [comment]
@bixel 
Implemented the feature, please review my pull request: https://github.com/pep-dortmund/member-database/pull/17

**Comment by The-Ludwig** [comment]
This issue is done, isn't it?

**Comment by maxnoe** [comment]
Yes
