### ISSUE TITLE
Admin interface cannot create new users

### ISSUE THREAD

**Issue by MaxNoe** [pep-dortmund/member-database#84]
The password hash is required and there is no easy way to produce it.

**Comment by bixel** [comment]
if you type anything into the password field, it will be hashed

**Comment by bixel** [comment]
...which is quite dangerous I just reckognised. Updating a user will unexpectedly update the password.

**Comment by MaxNoe** [comment]
Aha, then the field should be named password. Not password_hash. I assumed I had to hash it myself.

**Comment by bixel** [comment]
Yes true. But still this is a bug since *not* updating the password, but anything else will take the existing hash, and hash it again, locking out yourself 🙈

**Comment by MaxNoe** [comment]
Why is it even shown?   

The view has:   `column_list = ['username', 'person', 'roles']`

**Comment by MaxNoe** [comment]
https://stackoverflow.com/a/39190347/3838691

**Comment by bixel** [comment]
Ok that looks reasonably straight forward
